### ISSUE TITLE
Ducky Script

### ISSUE THREAD

**Issue by FalsePhilosopher** [bemxio/mario-head#1]
I wrote a ducky script for this, feel free to include it in your repo :)
https://github.com/FalsePhilosopher/BadUSB-Playground/blob/main/Ducky/USBRubberducky/destructive/Win/BSOD/Mario-Head/quack.txt

**Comment by bemxio** [comment]
ah, i just noticed it now, sorry for being late!
i will add it to the readme, thank you! :DDD
