### ISSUE TITLE
Can't run "pacman -S mingw-w64-gcc"

### ISSUE THREAD

**Issue by SilentSword123456** [bemxio/mario-head#10]
i run into a problem. 
after i installed MSYS2 on my windows 11 computer i tried to run "pacman -S mingw-w64-gcc" but i get an error message:

$ mingw-w64-i686-make
-bash: mingw-w64-i686-make: command not found

could you please help me on how to resolve this ?

Thanks.

**Comment by bemxio** [comment]
ah thank you for reminding me, you must also install `mingw-w64-make` using pacman with the same command, `pacman -S mingw-w64-make`

after that, all should go smoothly, i need to add a mention for that in the README

**Comment by SilentSword123456** [comment]
And i also can't run the command "pacman -S mingw-w64-gcc" nor "pacman -S mingw-w64-make", gives the same error:
$ pacman -S mingw-w64-gcc
error: target not found: mingw-w64-gcc
---------------
$ pacman -S mingw-w64-make
error: target not found: mingw-w64-make

Can you help me again please?
Thank you.

**Comment by bemxio** [comment]
hmm, what about `mingw-w64-i686-gcc` and `mingw-w64-i686-make`? metapackages should install correctly but maybe something was changed along the way and now you cannot do that

**Comment by SilentSword123456** [comment]
Thank you, but I still can't run the command :"pacman -S mingw-w64-gcc", it gives the same error message:
$ pacman -S mingw-w64-gcc
error: target not found: mingw-w64-gcc

What can I do?

**Comment by bemxio** [comment]
try to install the packages i mentioned above then, `mingw-w64-i686-gcc` and `mingw-w64-i686-make`
if that doesn't work out i'll need to try to compile the project via MSYS2 myself
