### ISSUE TITLE
One question

### ISSUE THREAD

**Issue by shellduck8** [bemxio/mario-head#3]
One question, is it harmful to your computer or does it just leave a bluescreen and when the computer restarts it is fine.

**Comment by bemxio** [comment]
well, it depends on what the system was doing when it got a BSoD. just be sure to save any stuff you were working on before doing it
most of the time it will all be good, so you don't need to worry

**Comment by shellduck8** [comment]
> well, it depends on what the system was doing when it got a BSoD. just be sure to save any stuff you were working on before doing it most of the time it will all be good, so you don't need to worry

Is windows 10 education and windows 11 home good?

**Comment by bemxio** [comment]
yup, it is supported from Windows XP to Windows 11
