### ISSUE TITLE
how do I compile

### ISSUE THREAD

**Issue by shellduck8** [bemxio/mario-head#9]
I've installed mingw-w64, I ran the command pacman -S mingw-w64-gcc once the terminal was opened. It succesfully installed, but when I try the make command it doesn't work. I've tried both windows and the mingw terminal ( and the last one I somehow can't change directory) and both don't work. I've tried every bin folder and added it to path, still doesn't work. I've searched up the make command and IT DOESNT EVEN COME WITH MINGW. Help me please.

**Comment by bemxio** [comment]
oh right, in case of MSYS2, you also need to seperately install `mingw-w64-make`
after that the `mingw-w64-i686-make` command should work and the project should build as normal
if you get any errors please show them

**Comment by shellduck8** [comment]
So, can you put that in the setup please? I'll update if it works.

**Comment by bemxio** [comment]
yeah, if that was the issue I'll fix the README once I have a chance to

**Comment by bemxio** [comment]
were you successful in compiling the project?
